### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by gmoneyomics** [JohnReid/pyseqan#1]
Hi, 

I am running pip install pyseqan on a MacOS High Sierra 

this is the error: 

Collecting pyseqan
  Using cached https://files.pythonhosted.org/packages/b1/07/bfcd2f58723f4f1b823c2e4d5519edfe77624408239f4a4615a9cb37338b/pyseqan-1.1.8.tar.gz
    Complete output from command python setup.py egg_info:
    *************************************************************
    *** I have detected that you have not run configure.py.
    *************************************************************
    *** Additionally, no global config files were found.
    *** I will go ahead with the default configuration.
    *** In all likelihood, this will not work out.
    ***
    *** See README_SETUP.txt for more information.
    ***
    *** If the build does fail, just re-run configure.py with the
    *** correct arguments, and then retry. Good luck!
    *************************************************************
    *** HIT Ctrl-C NOW IF THIS IS NOT WHAT YOU WANT
    *************************************************************
    Continuing in 1 seconds...    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/hf/j2143vs53ws8b3_4nyc0kghm0000gs/T/pip-install-u0aje4gz/pyseqan/setup.py", line 152, in <module>
        main()
      File "/private/var/folders/hf/j2143vs53ws8b3_4nyc0kghm0000gs/T/pip-install-u0aje4gz/pyseqan/setup.py", line 64, in main
        ] + conf['BOOST_INC_DIR'] + [os.path.join(conf['SEQAN_DIR'], 'include')]
      File "/anaconda3/envs/py3/lib/python3.7/posixpath.py", line 80, in join
        a = os.fspath(a)
    TypeError: expected str, bytes or os.PathLike object, not NoneType
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/hf/j2143vs53ws8b3_4nyc0kghm0000gs/T/pip-install-u0aje4gz/pyseqan/

I have tried reinstalling pip and upgrading pip, any idea what could be going wrong here?

**Comment by JohnReid** [comment]
I have to admit I'm not sure. You could try configuring all the directories that it wants manually. I guess one of the `conf['<KEY>']` is `None`

**Comment by gmoneyomics** [comment]
I ended up just installing on a linux system to get around the problem

**Comment by JohnReid** [comment]
Sorry you had to go to those lengths. I don't have access to a Mac so it is difficult for me to know what is wrong.

**Comment by gmoneyomics** [comment]
Seemed like a problem with the boost compiler on the MacOS, but worked great once I got it installed on a linux OS!
